#lang racket/base
(require "base-fsm-error-types.rkt"
         "../syntax-value-struct.rkt")

(provide warn:fsm:app:regexp?
         (struct-out warn:fsm:app:regexp:invalid-words)
         (struct-out warn:fsm:app:regexp:accept)
         (struct-out warn:fsm:app:regexp:reject))

(struct warn:fsm:app:regexp warn:fsm:app ())

(struct warn:fsm:app:regexp:invalid-words warn:fsm:app:regexp ()
  #:methods gen:printable-fsm-err-vals
  [(define (named-multi-failure err-struct)
     (foldl (lambda (val accum)
              (string-append accum (format "\n~a" val)))
            (format "The design recipe has not been successfully completed. The following words contain elements not in the alphabet of the regular expression ~s:."
                    (syntax-e (val-stx-pair-stx (warn:fsm-fsm-expr err-struct))))
            (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct))))
   (define (named-single-failure err-struct)
     (format "The design recipe has not been successfully completed. The following word contains elements not in the alphabet of the regular expression ~s:\n~a."
             (syntax-e (val-stx-pair-stx (warn:fsm-fsm-expr err-struct)))
             (car (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct)))))
   (define (anonymous-multi-failure err-struct)
     (foldl (lambda (val accum)
              (string-append accum (format "\n~a" val)))
            (format "The design recipe has not been successfully completed. The following words contain elements not in the alphabet of the regular expression:."
                    )
            (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct))))
   (define (anonymous-single-failure err-struct)
     (format "The design recipe has not been successfully completed. The following word contains elements not in the alphabet of the regular expression:\n~a."
             
             (car (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct)))))])

(struct warn:fsm:app:regexp:accept warn:fsm:app:regexp ()
  #:methods gen:printable-fsm-err-vals
  [(define (named-multi-failure err-struct)
     (foldl (lambda (val accum)
              (string-append accum (format "\n~a" val)))
            (format "The design recipe has not been successfully completed. The following words are not generated by the regular expression ~s:."
                    (syntax-e (val-stx-pair-stx (warn:fsm-fsm-expr err-struct))))
            (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct))))
   (define (named-single-failure err-struct)
     (format "The design recipe has not been successfully completed. The following word is not generated by the regular expression ~s:\n~a."
             (syntax-e (val-stx-pair-stx (warn:fsm-fsm-expr err-struct)))
             (car (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct)))))
   (define (anonymous-multi-failure err-struct)
     (foldl (lambda (val accum)
              (string-append accum (format "\n~a" val)))
            (format "The design recipe has not been successfully completed. The following words are not generated by the regular expression:."
                    )
            (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct))))
   (define (anonymous-single-failure err-struct)
     (format "The design recipe has not been successfully completed. The following word is not generated by the regular expression:\n~a."
             
             (car (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct)))))])

(struct warn:fsm:app:regexp:reject warn:fsm:app:regexp ()
  #:methods gen:printable-fsm-err-vals
  [(define (named-multi-failure err-struct)
     (foldl (lambda (val accum)
              (string-append accum (format "\n~a" val)))
            (format "The design recipe has not been successfully completed. The following words are generated by the regular expression ~s:."
                    (syntax-e (val-stx-pair-stx (warn:fsm-fsm-expr err-struct))))
            (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct))))
   (define (named-single-failure err-struct)
     (format "The design recipe has not been successfully completed. The following word is generated by the regular expression ~s:\n~a."
             (syntax-e (val-stx-pair-stx (warn:fsm-fsm-expr err-struct)))
             (car (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct)))))
   (define (anonymous-multi-failure err-struct)
     (foldl (lambda (val accum)
              (string-append accum (format "\n~a" val)))
            (format "The design recipe has not been successfully completed. The following words are generated by the regular expression:."
                    )
            (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct))))
   (define (anonymous-single-failure err-struct)
     (format "The design recipe has not been successfully completed. The following word is generated by the regular expression:\n~a."
             
             (car (map val-stx-pair-val (warn:fsm:app-err-exprs err-struct)))))])