#lang racket
;; all the testing grammars


(require "cfg-test-invs.rkt"
         "rg-test-invs.rkt"
         
         "../grammar-getters.rkt"
          "../rg-constructors.rkt"
         "../regular-grammar.rkt"
         "../constants.rkt"

          "../cfg-struct.rkt"
         "../cfg-constructors.rkt"
         "../constants.rkt"

         
         rackunit)


;; word word -> Boolean
;; Purpose: Determine if the second given word appears in
;;          the first given word
(define (contains? w pattern)
  (cond [(< (length w) (length pattern)) #f]
        [(equal? (take w (length pattern)) pattern) #t]
        [else (contains? (rest w) pattern)]))






;                          
;                          
;                          
;   ;;;;;     ;;;;         
;    ;   ;   ;   ;         
;    ;   ;  ;        ;;;;; 
;    ;   ;  ;       ;    ; 
;    ;;;;   ;   ;;;  ;;;;  
;    ;  ;   ;    ;       ; 
;    ;   ;   ;   ;  ;    ; 
;   ;;;   ;   ;;;   ;;;;;  
;                          
;                          
;                          
;                          
                                                                                      


;; L =  U ba*

;; syntactic categories
;; S: words in EMP U ba*
;; A : words in a*
(define EMP-U-ba* (make-rg '(S A)
                           '(a b)
                           `((S -> ,EMP)
                            (S -> b)
                            (S -> bA)
                            (A -> a)
                            (A -> aA))
                           'S))
;; Tests for EMP-U-ba*
#;(check-equal? (grammar-derive EMP-U-ba* '(a))
              "(a) is not in L(G).")
#;(check-equal? (grammar-derive EMP-U-ba* '(a b b a a))
              "(a b b a a) is not in L(G).")
#;(check-equal? (grammar-derive EMP-U-ba* '())
              '(S -> ε))
#;(check-equal? (grammar-derive EMP-U-ba* '(b a))
              '(S -> bA -> ba))
#;(check-equal? (grammar-derive EMP-U-ba* '(b a a a))
              '(S -> bA -> baA -> baaA -> baaa))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-EMP-U-ba* w)
  (or (empty? w)
      (and (eq? (first w) 'b)
           (andmap (λ (x) (eq? x 'a)) (rest w)))))

;(check-inv-holds? S-INV-EMP-U-ba* '() '(b) '(b a a) '(b a a a a a a a))
;(check-inv-fails? S-INV-EMP-U-ba* '(a) '(a b a a a b))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by A
(define (A-INV-EMP-U-ba* w)
  (andmap (λ (x) (eq? x 'a)) w))

;(check-inv-holds? A-INV-EMP-U-ba* '() '(a) '(a a) '(a a a a a a a))
;(check-inv-fails? A-INV-EMP-U-ba* '(b a) '(a b a a a b))


(define loi-EMP-U-ba* (list (list 'S S-INV-EMP-U-ba*)
                            (list 'A A-INV-EMP-U-ba*)))

;; L = {w | the number of as in w is a multiple of 3}

;; Syntactic categories
;; S = words with 3n as
;; B = words with 3n + 2 as
;; C = words with 3n + 1 as

(define MULT3-as (make-rg '(S B C)
                          '(a b)
                          `((S -> ,EMP)
                            (S -> aB)
                            (S -> bS)
                            (B -> aC)
                            (B -> bB)
                            (C -> aS)
                            (C -> bC))
                          'S))

;; Tests for MULT3-as
;(check-equal? (grammar-derive MULT3-as '(b b a b b))
;              "(b b a b b) is not in L(G).")
;(check-equal? (grammar-derive MULT3-as '(b b a b b a))
;              "(b b a b b a) is not in L(G).")
;(check-equal? (grammar-derive MULT3-as '(b b a b a b a a b))
;              "(b b a b a b a a b) is not in L(G).")
;(check-equal? (grammar-derive MULT3-as '())
;              `(S -> ,EMP))
;(check-equal? (grammar-derive MULT3-as '(a a a))
;              `(S -> aB -> aaC -> aaaS -> aaa))
;(check-equal? (grammar-derive MULT3-as '(b b a a b a b b))
;              `(S -> bS -> bbS -> bbaB -> bbaaC -> bbaabC ->
;                bbaabaS -> bbaababS -> bbaababbS ->  bbaababb))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-MULT3-as w)
  (let [(As (filter (λ (x) (eq? 'a x)) w))]
        (= 0 (remainder (length As) 3))))

;(check-inv-holds? S-INV-MULT3-as '() '(b) '(b a a a) '(b a a a a a a b))
;(check-inv-fails? S-INV-MULT3-as '(a) '(a b a a a b))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by B
(define (B-INV-MULT3-as w)
  (let [(As (filter (λ (x) (eq? 'a x)) w))]
        (= 2 (remainder (length As) 3))))

;(check-inv-holds? B-INV-MULT3-as '(a a) '(b a a) '(b a a a a a b))
;(check-inv-fails? B-INV-MULT3-as '(a) '(a b a a a b))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by C
(define (C-INV-MULT3-as w)
  (let [(As (filter (λ (x) (eq? 'a x)) w))]
        (= 1 (remainder (length As) 3))))

;(check-inv-holds? C-INV-MULT3-as '(a) '(b a) '(b a a a a b))
;(check-inv-fails? C-INV-MULT3-as '(a a) '(a b a a a a a b))


(define loi-MULT3-as (list (list 'S S-INV-MULT3-as)
                           (list 'B B-INV-MULT3-as)
                           (list 'C C-INV-MULT3-as)))

;; L = w does not contain aa

;; syntatic categories
;; S = words that do no contain aa
;; A = words that start with b and don't contain aa
;; B = words that start with b or a, and don't contain aa
(define NO-AA-grammer (make-rg '(S A B)
                               '(a b)
                               `((S -> ,EMP)
                                 (S -> aA)
                                 (S -> a)
                                 (S -> bB)
                                 (S -> b)
                                 (A -> bB)
                                 (A -> b)
                                 (B -> aA)
                                 (B -> a)
                                 (B -> b)
                                 (B -> bB))
                               'S))
                               



;(check-derive? NO-AA-grammer '() '(a) '(b) '(b b))

;(check-not-derive? NO-AA-grammer '(a a) '(a a a) '(b b a a) '(a a b b))



(define (S-INV-NO-AA-grammer ci)  
  (not (contains? ci '(a a))))


(define (A-INV-NO-AA-grammer ci)
  #;(and (equal? (drop ci (- (length ci) 1)) '(a))    
       (not (contains? ci '(a a))))
  (and (eq? (first ci) 'b)
       (not (contains? ci '(a a)))))

(define (B-INV-NO-AA-grammer ci)
  (and (not (contains? ci '(a a)))
       (or (eq? (first ci) 'b)
           (eq? (first ci) 'a))))


(define loi-NO-AA-grammer (list (list 'S S-INV-NO-AA-grammer)
                                (list 'A A-INV-NO-AA-grammer)
                                (list 'B B-INV-NO-AA-grammer)
                                ))

;(grammar-viz NO-AA-grammer '(a b a b b b a b a b b a) (list 'S S-INV-grammar) (list 'A A-INV-grammar) (list 'B B-INV-grammar))


;; L = w contains an even number of bs

;; syntactic categories
;; S: even number of bs
;; F: odd number of bs

(define EVEN-NUM-Bs-grammar
  (make-rg '(S F)
           '(a b)
           `((S -> ,EMP)
             (S -> aS)
             (S -> bF)
             (S -> a)
             (F -> aF)
             (F -> bS))
           'S))


;(check-derive? EVEN-NUM-Bs-grammar '() '(a) '(b b) '(b b b b))

;(check-not-derive? EVEN-NUM-Bs-grammar '(a b a) '(a b a a) '(b b a b a) '(a b b b a b b))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-EVEN-NUM-Bs-grammar w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))]
        (even? (length Bs))))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by F
(define (F-INV-EVEN-NUM-Bs-grammar w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))]
        (odd? (length Bs))))

(define loi-EVEN-NUM-Bs-grammar (list (list 'S S-INV-EVEN-NUM-Bs-grammar)
                                      (list 'F F-INV-EVEN-NUM-Bs-grammar)))

;; L = {w | w has an even number of and an odd number of b}

;; syntactic categories:
;; S: even number of a and odd number of b, start state
;; M: odd number of a and even number of b
;; N: even number of a and even number of b, final state
;; P: odd number of a and odd number of b
(define EVEN-A-ODD-B-grammar (make-rg '(S M N P)
                                      '(a b)
                                      `((S -> aP)
                                        (S -> bN)
                                        (M -> aN)
                                        (M -> bP)
                                        (N -> aM)
                                        (N -> bS)
                                        (P -> aS)
                                        (P -> bM)
                                        (S -> b)
                                        (M -> a))
                                      'S))

;(check-derive? EVEN-A-ODD-B-grammar '() '(a a b) '(b b) '(b b b b))
;(check-not-derive? EVEN-A-ODD-B-grammar '(a b a a) '(a b a a) '(b b a b b a) '(a b b a b a b b))


(define (S-INV-EVEN-A-ODD-B-grammar a-word)
  (and (even? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (M-INV-EVEN-A-ODD-B-grammar a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (N-INV-EVEN-A-ODD-B-grammar a-word)
  (and (even? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (P-INV-EVEN-A-ODD-B-grammar a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))


(define loi-EVEN-A-ODD-B-grammar (list (list 'S P-INV-EVEN-A-ODD-B-grammar)
                                       (list 'M M-INV-EVEN-A-ODD-B-grammar)
                                       (list 'N N-INV-EVEN-A-ODD-B-grammar)
                                       (list 'P P-INV-EVEN-A-ODD-B-grammar)))

;; L = (a)+(b)+(c)+ d
;; syntactic categories
;; S: w = (a)+(b)+(c)+ d
;; A: w = (b)+(c)+ d
;; B: w= (c)+ d
;; C: w= d
(define a+b+c+d (make-rg '(S A B C)
                         '(a b c d)
                         `((S -> aA)
                           (S -> aS)
                           (A -> bB)
                           (A -> bA)
                           (B -> cC)
                           (B -> cB)
                           (C -> d))
                         'S))


;(check-derive? a+b+c+d '(a a b c c d) '(a a b b b c c c d) '(a b c d) '(a a a a a a b b b b c c c c c d))
;(check-not-derive? a+b+c+d '(a) '(b) '(c) '(d) '(a a b b d))


;; invariants for a+b+c+d

;; S: w = (a)+(b)+(c)+ d
(define (S-INV-a+b+c+d ci)
  (if (empty? ci)
      #f
      (let*[(as (takef ci (λ (x) (eq? x 'a))))
            (bs (takef (drop ci (length as)) (λ (x) (eq? x 'b))))
            (cs (takef (drop ci (+ (length bs) (length as))) (λ (x) (eq? x 'c))))
            (d (first (drop ci (+ (length cs) (length bs) (length as)))))]
        (equal? ci (append as bs cs (list d))))))

;; A: w = (b)+(c)+ d
(define (A-INV-a+b+c+d ci)
  (let*[(bs (takef ci (λ (x) (eq? x 'b))))
        (cs (takef (drop ci (length bs)) (λ (x) (eq? x 'c))))
        (d (first (drop ci (+ (length cs) (length bs)))))]
    (equal? ci (append bs cs (list d)))))


;; B: w= (c)+ d
(define (B-INV-a+b+c+d ci)
  (let*[(cs (takef ci (λ (x) (eq? x 'c))))
        (d (first (drop ci (length cs))))]
    (equal? ci (append cs (list d)))))


;; C: w= d
(define (C-INV-a+b+c+d ci)
    (equal? ci '(d)))


(define loi-a+b+c+d (list (list 'S S-INV-a+b+c+d)
                          (list 'A A-INV-a+b+c+d)
                          (list 'B B-INV-a+b+c+d)
                          (list 'C C-INV-a+b+c+d)))




;; syntactic categories:
;; S: word contains abba
;; A: word starts with abb
;; B: word starts with ab
;; C: word starts with a
;; D: (a U b)+
(define CONTAINS-ABBA (make-rg  '(S A B C D)
                                '(a b)
                                `( (S ,ARROW aA) (S ,ARROW bS)
                                   (A ,ARROW aA) (A ,ARROW bB)
                                   (B ,ARROW aA) (B ,ARROW bC)
                                   (C ,ARROW aD) (C ,ARROW bS)
                                   (D ,ARROW aD) (D ,ARROW bD)
                                   (D ,ARROW a)  (D ,ARROW b))
                                'S
                                #:rejects (list '(b) '(a) '(a a) '(a b b) '(a b b b))
                                #:accepts (list '(a b b a a) '(a a b b a a))))


(define (S-INV-CONTAINS-ABBA w)
  (contains? w '(a b b a)))

(define (A-INV-CONTAINS-ABBA w)
  (or (contains? w '(a b b a))
      (and (<= 3 (length w))
           (equal? '(b b a) (take w 3)))))

(define (B-INV-CONTAINS-ABBA w)
  (or (contains? w '(a b b a))
      (and (<= 2 (length w))
           (equal? '(b a) (take w 2)))))

(define (C-INV-CONTAINS-ABBA w)
  (or (contains? w '(a b b a))
      (and (<= 1 (length w))
           (equal? '(a) (take w 1)))))

(define (D-INV-CONTAINS-ABBA w)
  (<= 1 (length w)))


(define loi-CONTAINS-ABBA (list (list 'S S-INV-CONTAINS-ABBA)
                                (list 'A A-INV-CONTAINS-ABBA)
                                (list 'B B-INV-CONTAINS-ABBA)
                                (list 'C C-INV-CONTAINS-ABBA)
                                (list 'D D-INV-CONTAINS-ABBA)))


;; S = word contains even b and odd a
;; A = word contains even b and even a
;; B = word contains odd b and odd a, final terminal
;; C = word contains odd b and even a
(define EVEN-B-ODD-A
  (make-rg '(S A B C)
           '(a b)
           `((S ,ARROW aA)
             (S ,ARROW bB)
             (S ,ARROW a)

             (A ,ARROW aS)
             (A ,ARROW bC)

             (B ,ARROW aC)
             (B ,ARROW bS)

             (C ,ARROW aB)
             (C ,ARROW bA)
             (C ,ARROW b))
           'S))



(define (S-INV-EVEN-B-ODD-A a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (A-INV-EVEN-B-ODD-A a-word)
  (and (even? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (B-INV-EVEN-B-ODD-A a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (C-INV-EVEN-B-ODD-A a-word)
  (and (even? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define loi-EVEN-B-ODD-A (list (list 'S S-INV-EVEN-B-ODD-A)
                               (list 'A A-INV-EVEN-B-ODD-A)
                               (list 'B B-INV-EVEN-B-ODD-A)
                               (list 'C C-INV-EVEN-B-ODD-A)))

;; syntactic categories
;;  S = words that start with aa, starting nonterminal
;;  A = words that start with a
;;  B = words that start with either a or b
(define rg-STARTS-WITH-aa (make-rg '(S A B) 
                                   '(a b) 
                                   '((S -> aA)
                                     (A -> a)
                                     (A -> aB)
                                     (B -> a)
                                     (B -> aB)
                                     (B -> b)
                                     (B -> bB))
                                   'S))

;; invariants

;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-rg-STARTS-WITH-aa w)
  (<= 2 (length (takef w (λ (x) (eq? 'a x))))))

;(check-inv-holds? S-INV-rg-STARTS-WITH-aa '(a a) '(a a a b) '(a a a b b))
;(check-inv-fails? S-INV-rg-STARTS-WITH-aa '() '(b) '(b b a) '(b a a b a))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by A
(define (A-INV-rg-STARTS-WITH-aa w)
  (<= 1 (length (takef w (λ (x) (eq? 'a x))))))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by B
(define (B-INV-rg-STARTS-WITH-aa w)
  (and (<= 1 (length w))
       (equal? w (takef w (λ (x) (or (eq? 'b x)
                                     (eq? 'a x)))))))

;(check-inv-holds? B-INV-rg-STARTS-WITH-aa '(a) '(b) '(b a a) '(a b a b))
;(check-inv-fails? B-INV-rg-STARTS-WITH-aa '())

(define loi-rg-STARTS-WITH-aa (list (list 'S S-INV-rg-STARTS-WITH-aa)
                                    (list 'A A-INV-rg-STARTS-WITH-aa)
                                    (list 'B B-INV-rg-STARTS-WITH-aa)
                                    ))

;; syntactic categories:
;; S: (bba)*
;; A: ba(bba)*
;; B: a(bba)*

(define bba-* (make-rg '(S A B) 
                       '(a b) 
                       `((S -> bA)
                         (S -> ,EMP)
                         (A -> bB)
                         (B -> aS))
                       'S))
;; invariants

;; word -> boolean
;; purpose: to determine if w ought to be generated by S
;; S = (bba)*
(define (S-INV-bba-* w)
  (cond
    [(empty? w) #t]
    [(and (>= (length w) 3)
          (eq? 'b (first w))
          (eq? 'b (second w))
          (eq? 'a (third w)))
     (S-INV-bba-* (drop w 3))]
    [else #f]))


;; word -> boolean
;; purpose: to determine if w ought to be generated by A
;; A = ba(bba)*
(define (A-INV-bba-* w)
  (and (>= (length w) 2)
       (eq? 'b (first w))
       (eq? 'a (second w))
       (S-INV-bba-* (drop w 2))))


;; word -> boolean
;; purpose: to determine if w ought to be generated by B
;; B = a(bba)*
(define (B-INV-bba-* w)
  (and (>= (length w) 1)
       (eq? 'a (first w))
       (S-INV-bba-* (rest w))))


(define loi-bba-* (list (list 'S S-INV-bba-*)
                                    (list 'A A-INV-bba-*)
                                    (list 'B B-INV-bba-*)))


;                                  
;                                  
;                                  
;     ;;;;  ;;;;;;    ;;;;         
;    ;   ;   ;   ;   ;   ;         
;   ;        ; ;    ;        ;;;;; 
;   ;        ;;;    ;       ;    ; 
;   ;        ; ;    ;   ;;;  ;;;;  
;   ;        ;      ;    ;       ; 
;    ;   ;   ;       ;   ;  ;    ; 
;     ;;;   ;;;       ;;;   ;;;;;  
;                                  
;                                  
;                                  
;                                  




;; Syntactic categories:
;; S: number of bs is greater than the amount of as
;; A: number of bs is greater than or equal to the number of as
(define numb>numa
  (make-cfg '(S A)
            '(a b)
            `((S ,ARROW b)
              (S ,ARROW AbA)
              (A ,ARROW AaAbA)
              (A ,ARROW AbAaA)
              (A ,ARROW ,EMP)
              (A ,ARROW bA))
            'S))

(define (S-INV-numb>numa w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
    (> (length Bs) (length As))))


(define (A-INV-numb>numa w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
    (>= (length Bs) (length As))))

(define loi-numb>numa (list (list 'S S-INV-numb>numa)
                            (list 'A A-INV-numb>numa)))


;; syntactic categories
;; S: word is a palindrome
(define palindrome
  (make-cfg '(S)
            '(a b)
            `((S ,ARROW ,EMP)
              (S ,ARROW aSa)
              (S ,ARROW bSb)
              (S ,ARROW a)
              (S ,ARROW b))
            'S))

(define (S-INV-palindrome w)
  (equal? w (reverse w)))

(define loi-palindrome (list (list 'S S-INV-palindrome)))


;; Syntactic categories
;; S: word is c^mb^na^nd^m
;; A: word is b^na^n
(define c^mb^na^nd^m
  (make-cfg '(S A)
            '(a b c d)
            `((S -> cSd)
              ;(S -> cAd)
              (S -> A)
              (A -> ,EMP)
              (A -> bAa))
            'S))

;;unit tests 
;(check-derive? c^mb^na^nd^m '() '(c d) '(b a) '(c b a d) '(c c b a d d))
;(check-not-derive? c^mb^na^nd^m '(c) '(a) '(b) '(d) '(c d d) '(a d) '(c b b a d))

;; invariants

;; word -> boolean
;; purpose: to determine if given word ought to be generated by S
(define (S-INV-c^mb^na^nd^m w)
  (let* ([Cs (takef w (λ (x) (eq? 'c x)))]
         [Bs (takef (drop w (length Cs)) (λ (x) (eq? 'b x)))]
         [As (takef (drop w (+ (length Bs) (length Cs))) (λ (x) (eq? 'a x)))]
         [Ds (takef (drop w (+ (length As) (length Bs) (length Cs))) (λ (x) (eq? 'd x)))])
    (and (append Cs Bs As Ds)
         (= (length Cs) (length Ds))
         (= (length Bs) (length As)))))
  

;; word -> boolean
;; purpose: to determine if given word ought to be generated by A
(define (A-INV-c^mb^na^nd^m w)
  (let* ([Bs (takef w (λ (x) (eq? 'b x)))]
         [As (takef (drop w (length Bs)) (λ (x) (eq? 'a x)))])
    (and (append Bs As)
         (= (length Bs) (length As)))))
  
(define loi-c^mb^na^nd^m (list (list 'S S-INV-c^mb^na^nd^m)
                               (list 'A A-INV-c^mb^na^nd^m)))


;; syntactic categories
;; S: word is wcw^r
(define wcw^r
  (make-cfg '(S)
            '(a b c)
            `((S ,ARROW c)
              (S ,ARROW aSa)
              (S ,ARROW bSb)
              (S ,ARROW a)
              (S ,ARROW b))
            'S))

(define (S-INV-wcw^r w)
  (equal? w (reverse w)))

(define loi-wcw^r (list (list 'S S-INV-wcw^r)))


;; syntactic categories:
;; S: word is aibj, where i <= j
;; A: word has equal num as and bs
;; B: word is b*
(define aibj
  (make-cfg '(S A B)
            '(a b)
            `((S -> AB)
              (A -> aAb)
              (A -> ,EMP)
              (B -> bB)
              (B -> ,EMP))
            'S))



(define (S-INV-aibj w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
    (and (equal? w (append As Bs))
         (>= (length Bs) (length As)))))

(define (A-INV-aibj w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
    (and (equal? w (append As Bs))
         (= (length Bs) (length As)))))

(define (B-INV-aibj w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))]
    (equal? w Bs)))

(define loi-aibj (list (list 'S S-INV-aibj)
                       (list 'A A-INV-aibj)
                       (list 'B B-INV-aibj)))
                       


;syntactic categories:
;; S: word is aibj, where  i <= 2j
(define aibj2
  (make-cfg '(S A)
            '(a b)
            `((S -> ,EMP)
              (S -> aSb)
              (S -> aSbb))
            'S))

(define (S-INV-aibj2 w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
    (and (equal? w (append As Bs))
         (>= (* 2 (length Bs)) (length As)))))

(define loi-aibj2 (list (list 'S S-INV-aibj2)))



;;syntactic categories:
;; S: word is a^nb^n
(define anbn
  (make-cfg '(S)
            '(a b)
            `((S -> ,EMP)
              (S -> aSb))
            'S))

(define (S-INV-anbn w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
    (and (equal? w (append As Bs))
         (= (length Bs) (length As)))))

(define loi-anbn (list (list 'S S-INV-anbn)))


;;syntactic categories:
;; S: word is a^nb^ma^n
;; A: word is b*
(define anbman
  (make-cfg '(S A)
            '(a b)
            `((S -> ,EMP)
              (S -> aSa)
              (S -> aAa)
              (S -> A)
              (A -> b)
              (A -> bA))
            'S))

(define (S-INV-anbman w)
  (or (empty? w)
  (let* [(As1 (takef w (λ (x) (eq? 'a x))))
         (Bs (takef (drop w (length As1)) (λ (x) (eq? 'b x))))
         (As2 (takef (drop w (+ (length Bs) (length As1))) (λ (x) (eq? 'a x))))]
    (and (equal? w (append As1 Bs As2))
         (if (empty? Bs)
             (equal? w As1)
             (= (length As1) (length As2)))))))

(define (A-INV-anbman w)
  (let* [(Bs (filter (λ (x) (eq? 'b x)) w))]
    (and (equal? w Bs))))

(define loi-anbman (list (list 'S S-INV-anbman)
                         (list 'A A-INV-anbman)))


;;syntactic categories:
;; S: word is (a^nb^n)*
;; A: word is a^nb^n 
(define anbn-*
  (make-cfg '(S A)
            '(a b)
            `((S -> ,EMP)
              (S -> AS)
              (A -> ,EMP)
              (A -> aAb))
            'S))

(define (S-INV-anbn-* ci)
  (let* ([As (takef ci (λ (x) (eq? 'a x)))]
         [Bs (takef (drop ci (length As)) (λ (x) (eq? 'b x)))])
  (if (and (empty? (drop ci (+ (length Bs) (length As)))))
      (= (length As) (length Bs))
      (and (= (length As) (length Bs))
           (S-INV-anbn-* (drop ci (+ (length As) (length Bs))))))))

(define (A-INV-anbn-* w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
    (and (equal? w (append As Bs))
         (= (length Bs) (length As)))))

(define loi-anbn-* (list (list 'S S-INV-anbn-*)
                         (list 'A A-INV-anbn-*)))



;; syntactic categories
;; S: word is a^nb^mc^jd^k, where n+m = j+k
;; A: 
(define a^nb^mc^jd^k
  (make-cfg '(S A B C)
            '(a b c d)
            `((S -> aSd)
              (S -> A)
              (S -> B)
              (A -> aAc)
              (A -> B)
              (B -> bBc)
              (B -> ,EMP)
              (C -> bCd)
              (C -> B))
            'S))


(define (S-INV-a^nb^mc^jd^k w)
  (or (empty? w)
  (let* [(As (takef w (λ (x) (eq? 'a x))))
         (Bs (takef (drop w (length As)) (λ (x) (eq? 'b x))))
         (Cs (takef (drop w (+ (length Bs) (length As))) (λ (x) (eq? 'c x))))
         (Ds (takef (drop w (+ (length Cs) (length Bs) (length As))) (λ (x) (eq? 'd x))))]
    (and (equal? w (append As Bs Cs Ds))
         (= (+ (length As) (length Bs)) (+ (length Cs) (length Ds)))))))

(define loi-a^nb^mc^jd^k (list (list 'S S-INV-a^nb^mc^jd^k)
                               (list 'A (λ (x) #t))
                               (list 'B (λ (x) #t))
                               (list 'C (λ (x) #t))))


;                                                                                                  
;                                                                                                  
;                                                                                                  
;   ;;;;;;; ;;;;;;   ;;; ;  ;;;;;;;  ;;;;; ;;;  ;;;   ;;;;            ;;    ;;;;;   ;;;;;;    ;;   
;   ;  ;  ;  ;   ;  ;   ;;  ;  ;  ;    ;    ;;   ;   ;   ;             ;     ;   ;   ;   ;     ;   
;      ;     ; ;    ;          ;       ;    ; ;  ;  ;                 ; ;    ;   ;   ; ;      ; ;  
;      ;     ;;;     ;;;;      ;       ;    ; ;  ;  ;                 ; ;    ;   ;   ;;;      ; ;  
;      ;     ; ;         ;     ;       ;    ;  ; ;  ;   ;;;           ; ;    ;;;;    ; ;      ; ;  
;      ;     ;           ;     ;       ;    ;  ; ;  ;    ;            ;;;    ;  ;    ;        ;;;  
;      ;     ;   ;  ;;   ;     ;       ;    ;   ;;   ;   ;           ;   ;   ;   ;   ;   ;   ;   ; 
;     ;;;   ;;;;;;  ; ;;;     ;;;    ;;;;; ;;;  ;;    ;;;           ;;; ;;; ;;;   ; ;;;;;;  ;;; ;;;
;                                                                                                  
;                                                                                                  
;                                                                                                  
;                                                                                                  


(define NUM-TESTS-PER-GRAMMAR 50)
(struct test-case (name num-tests thunk))


;;REGULAR GRAMMARS
#;(define tests (list
               (test-case 'EMP-U-ba*
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs EMP-U-ba* loi-EMP-U-ba*)))
               
               (test-case 'MULT3-as
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs MULT3-as loi-MULT3-as)))

               (test-case 'NO-AA-grammer
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs NO-AA-grammer loi-NO-AA-grammer)))

               (test-case 'EVEN-NUM-Bs-grammar
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs EVEN-NUM-Bs-grammar loi-EVEN-NUM-Bs-grammar)))
               
               (test-case 'EVEN-A-ODD-B-grammar
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs EVEN-A-ODD-B-grammar loi-EVEN-A-ODD-B-grammar)))

               (test-case 'a+b+c+d
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs a+b+c+d loi-a+b+c+d)))
               
               
               (test-case 'CONTAINS-ABBA
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs CONTAINS-ABBA loi-CONTAINS-ABBA)))
               
               (test-case 'EVEN-B-ODD-A
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs EVEN-B-ODD-A loi-EVEN-B-ODD-A)))
               
               (test-case 'rg-STARTS-WITH-aa
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs rg-STARTS-WITH-aa loi-rg-STARTS-WITH-aa)))
               
               (test-case 'bba-*
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (rg-test-invs bba-* loi-bba-*)))
                    
               ))



;; CONTEXT-FREE-GRAMMARS
(define tests (list
               (test-case 'numb>numa
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  numb>numa loi-numb>numa)))
               
               (test-case 'palindrome
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  palindrome loi-palindrome)))

               (test-case 'c^mb^na^nd^m
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  c^mb^na^nd^m loi-c^mb^na^nd^m)))

               (test-case 'wcw^r
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  wcw^r loi-wcw^r)))
               
               (test-case 'aibj
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  aibj loi-aibj)))

               (test-case 'aibj2
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  aibj2 loi-aibj2)))
               
               
               (test-case 'anbn
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  anbn loi-anbn)))
               
               (test-case 'anbman
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  anbman loi-anbman)))
               
               (test-case 'anbn-*
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15  anbn-* loi-anbn-*)))
               
               (test-case 'a^nb^mc^jd^k
                          NUM-TESTS-PER-GRAMMAR
                          (lambda () (cfg-test-invs 15 a^nb^mc^jd^k loi-a^nb^mc^jd^k)))
                    
               ))




(define res
    (for/list ([test (in-list tests)])
      (displayln (test-case-name test))
      (let ([result (for/vector #:length (test-case-num-tests test)
                      ([test-num (in-range (test-case-num-tests test))])
                      (define-values (results-lst cpu-time real-time gc-time)
                        (time-apply (test-case-thunk test) '()))
                      (collect-garbage 'major)
                      (collect-garbage 'major)
                      real-time)])
        (println result)
        (list (test-case-name test)
              result))))


