#lang racket
;; all the testing grammars


(require "cfg-test-invs.rkt"
         "rg-test-invs.rkt"
         
         "../grammar-getters.rkt"
          "../rg-constructors.rkt"
         "../regular-grammar.rkt"
         "../constants.rkt"

         
         rackunit)


;; word word -> Boolean
;; Purpose: Determine if the second given word appears in
;;          the first given word
(define (contains? w pattern)
  (cond [(< (length w) (length pattern)) #f]
        [(equal? (take w (length pattern)) pattern) #t]
        [else (contains? (rest w) pattern)]))






;                          
;                          
;                          
;   ;;;;;     ;;;;         
;    ;   ;   ;   ;         
;    ;   ;  ;        ;;;;; 
;    ;   ;  ;       ;    ; 
;    ;;;;   ;   ;;;  ;;;;  
;    ;  ;   ;    ;       ; 
;    ;   ;   ;   ;  ;    ; 
;   ;;;   ;   ;;;   ;;;;;  
;                          
;                          
;                          
;                          
                                                                                      


;; L =  U ba*

;; syntactic categories
;; S: words in EMP U ba*
;; A : words in a*
(define EMP-U-ba* (make-rg '(S A)
                           '(a b)
                           `((S -> ,EMP)
                            (S -> b)
                            (S -> bA)
                            (A -> a)
                            (A -> aA))
                           'S))
;; Tests for EMP-U-ba*
#;(check-equal? (grammar-derive EMP-U-ba* '(a))
              "(a) is not in L(G).")
#;(check-equal? (grammar-derive EMP-U-ba* '(a b b a a))
              "(a b b a a) is not in L(G).")
#;(check-equal? (grammar-derive EMP-U-ba* '())
              '(S -> ε))
#;(check-equal? (grammar-derive EMP-U-ba* '(b a))
              '(S -> bA -> ba))
#;(check-equal? (grammar-derive EMP-U-ba* '(b a a a))
              '(S -> bA -> baA -> baaA -> baaa))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-EMP-U-ba* w)
  (or (empty? w)
      (and (eq? (first w) 'b)
           (andmap (λ (x) (eq? x 'a)) (rest w)))))

;(check-inv-holds? S-INV-EMP-U-ba* '() '(b) '(b a a) '(b a a a a a a a))
;(check-inv-fails? S-INV-EMP-U-ba* '(a) '(a b a a a b))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by A
(define (A-INV-EMP-U-ba* w)
  (andmap (λ (x) (eq? x 'a)) w))

;(check-inv-holds? A-INV-EMP-U-ba* '() '(a) '(a a) '(a a a a a a a))
;(check-inv-fails? A-INV-EMP-U-ba* '(b a) '(a b a a a b))




;; L = {w | the number of as in w is a multiple of 3}

;; Syntactic categories
;; S = words with 3n as
;; B = words with 3n + 2 as
;; C = words with 3n + 1 as

(define MULT3-as (make-rg '(S B C)
                          '(a b)
                          `((S -> ,EMP)
                            (S -> aB)
                            (S -> bS)
                            (B -> aC)
                            (B -> bB)
                            (C -> aS)
                            (C -> bC))
                          'S))

;; Tests for MULT3-as
;(check-equal? (grammar-derive MULT3-as '(b b a b b))
;              "(b b a b b) is not in L(G).")
;(check-equal? (grammar-derive MULT3-as '(b b a b b a))
;              "(b b a b b a) is not in L(G).")
;(check-equal? (grammar-derive MULT3-as '(b b a b a b a a b))
;              "(b b a b a b a a b) is not in L(G).")
;(check-equal? (grammar-derive MULT3-as '())
;              `(S -> ,EMP))
;(check-equal? (grammar-derive MULT3-as '(a a a))
;              `(S -> aB -> aaC -> aaaS -> aaa))
;(check-equal? (grammar-derive MULT3-as '(b b a a b a b b))
;              `(S -> bS -> bbS -> bbaB -> bbaaC -> bbaabC ->
;                bbaabaS -> bbaababS -> bbaababbS ->  bbaababb))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-MULT3-as w)
  (let [(As (filter (λ (x) (eq? 'a x)) w))]
        (= 0 (remainder (length As) 3))))

;(check-inv-holds? S-INV-MULT3-as '() '(b) '(b a a a) '(b a a a a a a b))
;(check-inv-fails? S-INV-MULT3-as '(a) '(a b a a a b))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by B
(define (B-INV-MULT3-as w)
  (let [(As (filter (λ (x) (eq? 'a x)) w))]
        (= 2 (remainder (length As) 3))))

;(check-inv-holds? B-INV-MULT3-as '(a a) '(b a a) '(b a a a a a b))
;(check-inv-fails? B-INV-MULT3-as '(a) '(a b a a a b))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by C
(define (C-INV-MULT3-as w)
  (let [(As (filter (λ (x) (eq? 'a x)) w))]
        (= 1 (remainder (length As) 3))))

;(check-inv-holds? C-INV-MULT3-as '(a) '(b a) '(b a a a a b))
;(check-inv-fails? C-INV-MULT3-as '(a a) '(a b a a a a a b))


;; L = w does not contain aa

;; syntatic categories
;; S = words that do no contain aa
;; A = words that start with b and don't contain aa
;; B = words that start with b or a, and don't contain aa
(define NO-AA-grammer (make-rg '(S A B)
                               '(a b)
                               `((S -> ,EMP)
                                 (S -> aA)
                                 (S -> a)
                                 (S -> bB)
                                 (S -> b)
                                 (A -> bB)
                                 (A -> b)
                                 (B -> aA)
                                 (B -> a)
                                 (B -> b)
                                 (B -> bB))
                               'S))
                               



;(check-derive? NO-AA-grammer '() '(a) '(b) '(b b))

;(check-not-derive? NO-AA-grammer '(a a) '(a a a) '(b b a a) '(a a b b))



(define (S-INV-NO-AA-grammer ci)  
  (not (contains? ci '(a a))))


(define (A-INV-NO-AA-grammer ci)
  #;(and (equal? (drop ci (- (length ci) 1)) '(a))    
       (not (contains? ci '(a a))))
  (and (eq? (first ci) 'b)
       (not (contains? ci '(a a)))))

(define (B-INV-NO-AA-grammer ci)
  (and (not (contains? ci '(a a)))
       (or (eq? (first ci) 'b)
           (eq? (first ci) 'a))))


;(grammar-viz NO-AA-grammer '(a b a b b b a b a b b a) (list 'S S-INV-grammar) (list 'A A-INV-grammar) (list 'B B-INV-grammar))


;; L = w contains an even number of bs

;; syntactic categories
;; S: even number of bs
;; F: odd number of bs

(define EVEN-NUM-Bs-grammar
  (make-rg '(S F)
           '(a b)
           `((S -> ,EMP)
             (S -> aS)
             (S -> bF)
             (S -> a)
             (F -> aF)
             (F -> bS))
           'S))


;(check-derive? EVEN-NUM-Bs-grammar '() '(a) '(b b) '(b b b b))

;(check-not-derive? EVEN-NUM-Bs-grammar '(a b a) '(a b a a) '(b b a b a) '(a b b b a b b))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-EVEN-NUM-Bs-grammar w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))]
        (even? (length Bs))))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by F
(define (F-INV-EVEN-NUM-Bs-grammar w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))]
        (odd? (length Bs))))


;; L = {w | w has an even number of and an odd number of b}

;; syntactic categories:
;; S: even number of a and even number of b, start state
;; M: odd number of a and odd number of b
;; N: even number of a and odd number of b, final state
;; P: odd number of a and even number of b

;; syntactic categories
;; S: even num as AND odd num bs
;; M: 

(define EVEN-A-ODD-B-grammar (make-rg '(S M N P)
                                      '(a b)
                                      `((S -> aP)
                                        (S -> ,EMP)
                                        (S -> bN)
                                        (S -> b)
                                        (M -> aN)
                                        (M -> a)
                                        (M -> bP)
                                        (N -> aM)
                                        (N -> bS)
                                        (P -> aS)
                                        (P -> bM))
                                      'S))

;(check-derive? EVEN-A-ODD-B-grammar '() '(a a b) '(b b) '(b b b b))
;(check-not-derive? EVEN-A-ODD-B-grammar '(a b a a) '(a b a a) '(b b a b b a) '(a b b a b a b b))


(define (S-INV-EVEN-A-ODD-B-grammar a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (M-INV-EVEN-A-ODD-B-grammar a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (N-INV-EVEN-A-ODD-B-grammar a-word)
  (and (even? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (P-INV-EVEN-A-ODD-B-grammar a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))


(rg-test-invs-andres EVEN-A-ODD-B-grammar  (list (list 'S S-INV-EVEN-A-ODD-B-grammar)
                                                (list 'M M-INV-EVEN-A-ODD-B-grammar)
                                                (list 'N N-INV-EVEN-A-ODD-B-grammar)
                                                (list 'P P-INV-EVEN-A-ODD-B-grammar)))


;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
#;(define (S-INV-EVEN-A-ODD-B-grammar w)
  (let [(Bs (filter (λ (x) (eq? 'b x)) w))
        (As (filter (λ (x) (eq? 'a x)) w))]
        (and (even? (length As))
             (odd? (length Bs)))))


;; S: even number of a and even number of b, start state
;; M: odd number of a and odd number of b
;; N: even number of a and odd number of b, final state
;; P: odd number of a and even number of b




;; L = (a)+(b)+(c)+ d
;; syntactic categories
;; S: w = (a)+(b)+(c)+ d
;; A: w = (b)+(c)+ d
;; B: w= (c)+ d
;; C: w= d
(define a+b+c+d (make-rg '(S A B C)
                         '(a b c d)
                         `((S -> aA)
                           (S -> aS)
                           (A -> bB)
                           (A -> bA)
                           (B -> cC)
                           (B -> cB)
                           (C -> d))
                         'S))


;(check-derive? a+b+c+d '(a a b c c d) '(a a b b b c c c d) '(a b c d) '(a a a a a a b b b b c c c c c d))
;(check-not-derive? a+b+c+d '(a) '(b) '(c) '(d) '(a a b b d))


;; invariants for a+b+c+d

;; S: w = (a)+(b)+(c)+ d
(define (S-INV-a+b+c+d ci)
  (if (empty? ci)
      #f
      (let*[(as (takef ci (λ (x) (eq? x 'a))))
            (bs (takef (drop ci (length as)) (λ (x) (eq? x 'b))))
            (cs (takef (drop ci (+ (length bs) (length as))) (λ (x) (eq? x 'c))))
            (d (first (drop ci (+ (length cs) (length bs) (length as)))))]
        (equal? ci (append as bs cs (list d))))))

;; A: w = (b)+(c)+ d
(define (A-INV-a+b+c+d ci)
  (let*[(bs (takef ci (λ (x) (eq? x 'b))))
        (cs (takef (drop ci (length bs)) (λ (x) (eq? x 'c))))
        (d (first (drop ci (+ (length cs) (length bs)))))]
    (equal? ci (append bs cs (list d)))))


;; B: w= (c)+ d
(define (B-INV-a+b+c+d ci)
  (let*[(cs (takef ci (λ (x) (eq? x 'c))))
        (d (first (drop ci (length cs))))]
    (equal? ci (append cs (list d)))))


;; C: w= d
(define (C-INV-a+b+c+d ci)
    (equal? ci '(d)))



(define CONTAINS-ABBA (make-rg  '(S A B C D)
                                '(a b)
                                `( (S ,ARROW aA) (S ,ARROW bS)
                                   (A ,ARROW aA) (A ,ARROW bB)
                                   (B ,ARROW aA) (B ,ARROW bC)
                                   (C ,ARROW aD) (C ,ARROW bS)
                                   (D ,ARROW aD) (D ,ARROW bD)
                                   (D ,ARROW a)  (D ,ARROW b))
                                'S
                                #:rejects (list '(b) '(a) '(a a) '(a b b) '(a b b b))
                                #:accepts (list '(a b b a a) '(a a b b a a))))



;; S = word contains even b and odd a
;; A = word contains even b and even a
;; B = word contains odd b and odd a, final terminal
;; C = word contains odd b and even a

(define EVEN-B-ODD-A (make-rg '(S A B C)
                              '(a b)
                              `( (S ,ARROW aB) (S ,ARROW bC)
                                 (S ,ARROW ,EMP)
                                 (A ,ARROW aC) (A ,ARROW bB)
                                 (A ,ARROW a)  (A ,ARROW b)
                                 (B ,ARROW aS) (B ,ARROW bA)
                                 (B ,ARROW a)  (B ,ARROW b)
                                 (C ,ARROW aA) (C ,ARROW bS)
                                 (C ,ARROW a)  (C ,ARROW b))
                              'S))



(define (S-INV a-word)
  (and (even? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (A-INV a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (B-INV a-word)
  (and (even? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (odd? (length (filter (λ (w) (equal? w 'b)) a-word)))))

(define (C-INV a-word)
  (and (odd? (length (filter (λ (w) (equal? w 'a)) a-word)))
       (even? (length (filter (λ (w) (equal? w 'b)) a-word)))))




;; syntactic categories
;;  S = words that start with aa, starting nonterminal
;;  A = words that start with a
;;  B = words that start with either a or b
(define rg-STARTS-WITH-aa (make-rg '(S A B) 
                                   '(a b) 
                                   '((S -> aA)
                                     (A -> a)
                                     (A -> aB)
                                     (B -> a)
                                     (B -> aB)
                                     (B -> b)
                                     (B -> bB))
                                   'S))

;; invariants

;; word -> boolean
;;purpose: to determine if a would ought to be generated by S
(define (S-INV-rg-STARTS-WITH-aa w)
  (<= 2 (length (takef w (λ (x) (eq? 'a x))))))

;(check-inv-holds? S-INV-rg-STARTS-WITH-aa '(a a) '(a a a b) '(a a a b b))
;(check-inv-fails? S-INV-rg-STARTS-WITH-aa '() '(b) '(b b a) '(b a a b a))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by A
(define (A-INV-rg-STARTS-WITH-aa w)
  (<= 1 (length (takef w (λ (x) (eq? 'a x))))))

;; word -> boolean
;;purpose: to determine if a would ought to be generated by B
(define (B-INV-rg-STARTS-WITH-aa w)
  (and (<= 1 (length w))
       (equal? w (takef w (λ (x) (or (eq? 'b x)
                                     (eq? 'a x)))))))

;(check-inv-holds? B-INV-rg-STARTS-WITH-aa '(a) '(b) '(b a a) '(a b a b))
;(check-inv-fails? B-INV-rg-STARTS-WITH-aa '())



;; have to make (bba)*









;                                  
;                                  
;                                  
;     ;;;;  ;;;;;;    ;;;;         
;    ;   ;   ;   ;   ;   ;         
;   ;        ; ;    ;        ;;;;; 
;   ;        ;;;    ;       ;    ; 
;   ;        ; ;    ;   ;;;  ;;;;  
;   ;        ;      ;    ;       ; 
;    ;   ;   ;       ;   ;  ;    ; 
;     ;;;   ;;;       ;;;   ;;;;;  
;                                  
;                                  
;                                  
;                                  
