#lang racket
(require 2htdp/image
         racket/runtime-path)
(provide (all-defined-out))

#;(define-runtime-path S-KEY-PATH "keyboard_key_s.png")
(define-runtime-path S-KEY-PATH "KEYBOARD-S-KEY.png")
;(define-runtime-path W-KEY-PATH "keyboard_key_w.png")
(define-runtime-path W-KEY-PATH "KEYBOARD-W-KEY.png")
(define-runtime-path R-KEY-PATH "KEYBOARD-R-KEY.png")
(define-runtime-path F-KEY-PATH "KEYBOARD-F-KEY.png")
(define-runtime-path E-KEY-PATH "KEYBOARD-E-KEY.png")
;(define-runtime-path A-KEY-PATH "KEYBOARD-A-KEY.svg")
(define-runtime-path A-KEY-PATH "KEYBOARD-A-KEY.png")
(define-runtime-path D-KEY-PATH "KEYBOARD-D-KEY.png")
(define-runtime-path ARROW-RIGHT-KEY-PATH "KEYBOARD-RIGHT-KEY.png")
(define-runtime-path ARROW-LEFT-KEY-PATH "KEYBOARD-LEFT-KEY.png")
(define-runtime-path ARROW-UP-KEY-PATH "KEYBOARD-UP-KEY.png")
;(define-runtime-path ARROW-DOWN-KEY-PATH "keyboard_key_down.png")
(define-runtime-path ARROW-DOWN-KEY-PATH "KEYBOARD-DOWN-KEY.png")

(define S-KEY (bitmap/file S-KEY-PATH))
(define W-KEY (bitmap/file W-KEY-PATH))
(define R-KEY (bitmap/file R-KEY-PATH))
(define F-KEY (bitmap/file F-KEY-PATH))
(define E-KEY (bitmap/file E-KEY-PATH))
(define A-KEY (bitmap/file A-KEY-PATH))
(define D-KEY (bitmap/file D-KEY-PATH))
(define ARROW-RIGHT-KEY (bitmap/file ARROW-RIGHT-KEY-PATH))
(define ARROW-LEFT-KEY (bitmap/file ARROW-LEFT-KEY-PATH))
(define ARROW-UP-KEY (bitmap/file ARROW-UP-KEY-PATH))
(define ARROW-DOWN-KEY (bitmap/file ARROW-DOWN-KEY-PATH))