name: Build
on: [push, pull_request]

jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
      working-directory: ./fsm-gui/electron-gui]
    - name: build
      run: npm run make
      working-directory: ./fsm-gui/electron-gui]

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
      working-directory: ./fsm-gui/electron-gui]
    - name: build
      run: npm run make
      working-directory: ./fsm-gui/electron-gui]

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
      working-directory: ./fsm-gui/electron-gui]
    - name: build
      run: npm run make
      working-directory: ./fsm-gui/electron-gui]
