name: Release_GUI
on:
  release:
    types:
      - created

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
      working-directory: ./fsm-gui/electron-gui
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
      working-directory: ./fsm-gui/electron-gui

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
      working-directory: ./fsm-gui/electron-gui
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
      working-directory: ./fsm-gui/electron-gui

  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
      working-directory: ./fsm-gui/electron-gui
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
      working-directory: ./fsm-gui/electron-gui
